name: 'Find Serverless Framework API`s inside a Turborepo (monorepo) repository'
description: 'This action loops through all the apps and find the serverless.yml files inside them.'
inputs:
  apps-directory:  # id of input
    description: 'The directory where the apps are located (in Turborepo it is the directory "apps").'
    required: true
    default: 'apps'
outputs:
  apps-directory: # id of output
    description: 'The directory of the apps'
runs:
  using: 'node16'
  main: 'dist/index.js'
